import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.scss"
import Header from "../components/Header"
import Acara from "../components/Acara"
import Kegiatan from "../components/KegiatanKami"
import JoinBGDC from "../components/JoinBGDC"
import Footer from "../components/Footer"
function App() {
    return (
        <>
            <Header />
            <Home />
            <Kegiatan />
            <Acara />
            <JoinBGDC />
            <Footer />
        </>
    )
}

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className=" w-full py-8">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                    <path
                        fill="#273036"
                        fill-opacity="1"
                        d="M0,288L40,282.7C80,277,160,267,240,245.3C320,224,400,192,480,165.3C560,139,640,117,720,117.3C800,117,880,139,960,154.7C1040,171,1120,181,1200,176C1280,171,1360,149,1400,138.7L1440,128L1440,0L1400,0C1360,0,1280,0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z"
                    ></path>
                </svg>
            </div>
        </div>
    )
}

export default App
